server:
  port: 9001

spring:
  application:
    name: bookingservice

  datasource:
    url: jdbc:mysql://100.120.107.63:3306/hms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  config:
    import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.hotelerp.frontoffice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{logId:-}] %-5level %logger{36} - %msg%n"

  file:
    name: logs/frontoffice-service.log

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

channex:
  api:
    url: ${CHANNEX_API_URL:https://staging.channex.io/api/v1}
    key: ${CHANNEX_API_KEY:uUvCy9UqkQ4cepNKuCu6+aeCkZdrCJrkchegSyvz6/4QK/6K7SoF92ZYzXHknppa}
    property-id: ${CHANNEX_PROPERTY_ID:3ac4f491-34c0-462e-95fd-acdf20006bdb}

